In [1]:
import os
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

# Read text file
with open("Sherlock Holmes.txt", "r", encoding="utf-8") as f:
    data = f.read()

# Tokenize
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

print("Vocabulary:", (tokenizer.word_index))

Vocabulary: {'the': 1, 'and': 2, 'i': 3, 'to': 4, 'of': 5, 'a': 6, 'in': 7, 'that': 8, 'it': 9, 'he': 10, 'you': 11, 'was': 12, 'his': 13, 'is': 14, 'my': 15, 'have': 16, 'as': 17, 'with': 18, 'had': 19, 'which': 20, 'at': 21, 'for': 22, 'but': 23, 'me': 24, 'not': 25, 'be': 26, 'we': 27, 'from': 28, 'there': 29, 'this': 30, 'said': 31, 'upon': 32, 'so': 33, 'holmes': 34, 'him': 35, 'her': 36, 'she': 37, "'": 38, 'very': 39, 'your': 40, 'been': 41, 'all': 42, 'on': 43, 'no': 44, 'what': 45, 'one': 46, 'then': 47, 'were': 48, 'by': 49, 'are': 50, 'an': 51, 'would': 52, 'out': 53, 'when': 54, 'up': 55, 'man': 56, 'could': 57, 'has': 58, 'do': 59, 'into': 60, 'mr': 61, 'who': 62, 'little': 63, 'will': 64, 'if': 65, 'some': 66, 'now': 67, 'see': 68, 'down': 69, 'should': 70, 'our': 71, 'or': 72, 'they': 73, 'may': 74, 'well': 75, 'am': 76, 'us': 77, 'over': 78, 'more': 79, 'think': 80, 'room': 81, 'know': 82, 'shall': 83, 'about': 84, 'can': 85, 'before': 86, 'must': 87, 'only': 88, 'come'

In [37]:
print(len(tokenizer.word_index))

8199


In [16]:
import re
sentences = re.split(r'[.\n]', data)
# print(sentences)
sentences = [s.strip() for s in sentences if s.strip()]
print(sentences)

['THE ADVENTURES OF SHERLOCK HOLMES', 'Arthur Conan Doyle', 'Table of contents', 'A Scandal in Bohemia', 'The Red-Headed League', 'A Case of Identity', 'The Boscombe Valley Mystery', 'The Five Orange Pips', 'The Man with the Twisted Lip', 'The Adventure of the Blue Carbuncle', 'The Adventure of the Speckled Band', "The Adventure of the Engineer's Thumb", 'The Adventure of the Noble Bachelor', 'The Adventure of the Beryl Coronet', 'The Adventure of the Copper Beeches', 'A SCANDAL IN BOHEMIA', 'Table of contents', 'Chapter 1', 'Chapter 2', 'Chapter 3', 'CHAPTER I', 'To Sherlock Holmes she is always the woman', 'I have seldom heard him', 'mention her under any other name', 'In his eyes she eclipses and', 'predominates the whole of her sex', 'It was not that he felt any', 'emotion akin to love for Irene Adler', 'All emotions, and that one', 'particularly, were abhorrent to his cold, precise but admirably', 'balanced mind', 'He was, I take it, the most perfect reasoning and', 'observing mac

In [20]:
input_seq=[]
for s in sentences:
    tokenized_sen=tokenizer.texts_to_sequences([s])[0]
    # print(tokenized_sen)
    for i in range(1,len(tokenized_sen)):
        input_seq.append(tokenized_sen[:i+1])


In [18]:
input_seq

[[1, 1561],
 [1, 1561, 5],
 [1, 1561, 5, 129],
 [1, 1561, 5, 129, 34],
 [647, 4498],
 [647, 4498, 4499],
 [226, 5],
 [226, 5, 1562],
 [6, 827],
 [6, 827, 7],
 [6, 827, 7, 871],
 [1, 234],
 [1, 234, 462],
 [1, 234, 462, 648],
 [6, 110],
 [6, 110, 5],
 [6, 110, 5, 2072],
 [1, 678],
 [1, 678, 1360],
 [1, 678, 1360, 499],
 [1, 294],
 [1, 294, 949],
 [1, 294, 949, 872],
 [1, 56],
 [1, 56, 18],
 [1, 56, 18, 1],
 [1, 56, 18, 1, 1014],
 [1, 56, 18, 1, 1014, 873],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 423],
 [1, 577, 5, 1, 423, 1361],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 1785],
 [1, 577, 5, 1, 1785, 763],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 3185],
 [1, 577, 5, 1, 3185, 649],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 764],
 [1, 577, 5, 1, 764, 1246],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 2073],
 [1, 577, 5, 1, 2073, 394],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 828],
 [1, 577, 5, 

Padding

In [24]:
max_length=max([len(x) for x in input_seq])

In [25]:
print(max_length)

17


In [27]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_seq=pad_sequences(input_seq,maxlen=max_length,padding='pre')

In [29]:
padded_input_seq

array([[   0,    0,    0, ...,    0,    1, 1561],
       [   0,    0,    0, ...,    1, 1561,    5],
       [   0,    0,    0, ..., 1561,    5,  129],
       ...,
       [   0,    0,    0, ...,   28,    1, 8198],
       [   0,    0,    0, ...,    1, 8198, 8199],
       [   0,    0,    0, ..., 8198, 8199, 3187]])

In [30]:
x=padded_input_seq[:,:-1]
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1, 1561],
       [   0,    0,    0, ...,    1, 1561,    5],
       ...,
       [   0,    0,    0, ...,  693,   28,    1],
       [   0,    0,    0, ...,   28,    1, 8198],
       [   0,    0,    0, ...,    1, 8198, 8199]])

In [34]:
y=padded_input_seq[:,-1]
y

array([1561,    5,  129, ..., 8198, 8199, 3187])

In [35]:
x.shape

(92203, 16)

In [36]:
y.shape

(92203,)

In [55]:
vocab_size = len(tokenizer.word_index) + 1


In [57]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=100, input_length=x.shape[1]),
    LSTM(128),
    Dense(vocab_size, activation='softmax')
])


model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)



In [58]:
model.summary()


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 16, 100)           820000    
                                                                 
 lstm_4 (LSTM)               (None, 128)               117248    
                                                                 
 dense_4 (Dense)             (None, 8200)              1057800   
                                                                 
Total params: 1,995,048
Trainable params: 1,995,048
Non-trainable params: 0
_________________________________________________________________


In [60]:
model.fit(x,y,epochs=20)

Epoch 1/20
2882/2882 [==============================] - 87s 30ms/step - loss: 4.7502 - accuracy: 0.1731
Epoch 2/20
2882/2882 [==============================] - 88s 31ms/step - loss: 4.4659 - accuracy: 0.1894
Epoch 3/20
2882/2882 [==============================] - 86s 30ms/step - loss: 4.2083 - accuracy: 0.2068
Epoch 4/20
2882/2882 [==============================] - 86s 30ms/step - loss: 3.9678 - accuracy: 0.2278
Epoch 5/20
2882/2882 [==============================] - 114s 40ms/step - loss: 3.7388 - accuracy: 0.2542
Epoch 6/20
2882/2882 [==============================] - 118s 41ms/step - loss: 3.5237 - accuracy: 0.2808
Epoch 7/20
2882/2882 [==============================] - 116s 40ms/step - loss: 3.3224 - accuracy: 0.3115
Epoch 8/20
2882/2882 [==============================] - 124s 43ms/step - loss: 3.1394 - accuracy: 0.3394
Epoch 9/20
2882/2882 [==============================] - 125s 43ms/step - loss: 2.9699 - accuracy: 0.3676
Epoch 10/20
2882/2882 [==============================] - 11

In [64]:
import time
import numpy as np
text="what is your"
for i in range(10):
    token_text=tokenizer.texts_to_sequences([text])[0]
    padded_token_text=pad_sequences([token_text],maxlen=16,padding='pre')
    pos=np.argmax(model.predict(padded_token_text))
    for word,index in tokenizer.word_index.items():
        if index==pos:
            text=text+" "+word
            print(text)
            time.sleep(2)

1/1 [==============================] - 0s 43ms/step
what is your reason
1/1 [==============================] - 0s 16ms/step
what is your reason for
1/1 [==============================] - 0s 16ms/step
what is your reason for i
1/1 [==============================] - 0s 17ms/step
what is your reason for i should
1/1 [==============================] - 0s 17ms/step
what is your reason for i should have
1/1 [==============================] - 0s 134ms/step
what is your reason for i should have acted
1/1 [==============================] - 0s 183ms/step
what is your reason for i should have acted in
1/1 [==============================] - 0s 17ms/step
what is your reason for i should have acted in the
1/1 [==============================] - 0s 17ms/step
what is your reason for i should have acted in the police
1/1 [==============================] - 0s 20ms/step
what is your reason for i should have acted in the police station
